all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net: 

  vars:
    proxy_domains: 
      - dev.diesel.net
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
