---
kind: pipeline
type: docker
name: Deploy coming-soon page (dev)

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest

  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/dev.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy coming-soon page (test)

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest

  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/test.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - stable
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy coming-soon page (prod)

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - production-latest
        - ${DRONE_TAG}

  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/prod.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - tag
...
